[Icon Theme]
Name=InfinityOS Radience
Comment=Radience for InfinityOS
Inherits=Adwaita
Example=folder

# KDE/Plasma Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,96,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,96,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256
FollowsColorScheme=true

KDE-Extensions=.svg

# Directory list
Directories=scalable/apps,scalable/actions,scalable/status,scalable/devices,scalable/places,scalable/mimetypes

[scalable/apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable
